spring:
  application.name: PharmacyManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy_db
    username: postgres
    password: ${your_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

#  devtools:
#
#    restart.enabled: true
#    livereload.enabled: true